spring:
  application:
    name: board-games
  datasource:
    url: jdbc:postgresql://localhost:5432/board-games
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: 8081